In [1]:
# Set up dependencies
import os
import pandas as pd

In [2]:
file_path = os.path.join('../Resources/weather_data.csv')
cities = pd.read_csv(file_path)

In [13]:
cities_df = pd.DataFrame(cities)
cities_df=cities_df.drop(columns="City ID")
cities_df

,City,Latitude,Longitude,Max Temp,Humidity,Cloudiness,Wind Speed,Country,Date
0,Ushuaia,-54.8000,-68.3000,51.93,96,100,6.31,AR,1584241200
1,Butaritari,3.0707,172.7902,83.88,74,0,11.79,KI,1584241200
2,Praia,14.9215,-23.5087,71.62,79,0,11.50,CV,1584241200
3,Puerto del Rosario,28.5004,-13.8627,58.62,77,0,10.40,ES,1584241200
4,Avarua,-21.2078,-159.7750,83.95,67,8,6.15,CK,1584241200
...,...,...,...,...,...,...,...,...,...
558,Aden,12.7794,45.0367,74.97,77,80,5.99,YE,1584241200
559,Richards Bay,-28.7830,32.0377,77.85,85,54,10.98,ZA,1584241200
560,Beira,-19.8436,34.8389,77.18,83,0,7.81,MZ,1584241200
561,Chitral,35.8462,71.7858,17.67,42,0,8.86,PK,1584241200
562,Ketchikan,55.3422,-131.6461,29.73,82,0,2.98,US,1584241200

In [14]:
cities_df.to_html('../Resources/weather_data.html')